# Usa la imagen oficial de Nginx
FROM nginx

# Copia el archivo index.html al directorio de documentos de Nginx
COPY index.html /usr/share/nginx/html/

# Expone el puerto 80 para que pueda ser accesible desde fuera del contenedor
EXPOSE 80
